### ISSUE TITLE
JDBC Roadmap

### ISSUE THREAD

**Issue by alex268** [ydb-platform/ydb-jdbc-driver#6]
Version 2.0
- [x]  Use the session pool for all operations
- [x]  Add support of cloud authentications
- [x]  Base support of positional arguments
- [x]  Auto-configure session pool size
- [x]  Auto-detect the execution mode by query type
- [x]  Implement levels of JDBC compliance - from low level for plain-YQL to high level to jdbc-like SQL
- [x]  Split implementations for prepared and non-prepared statements
- [x]  Support batch execution for prepared statement

Version 2.1
- [x]  Cache prepared queries
- [x]  Auto convertion batch queries to YQL with list parameter  

Further releases
- [x]  Support lazy asynchronous result sets
- [x]  Usage QueryService for query execution
- [x]  Support of scheme operatons
